### PR TITLE
Add the installation guide

### PR DESCRIPTION
**Pull request by PeanutPK**
# What did I do?
1. Add installation guide for both backend and frontend
2. Add sample.env for both the backend and the frontend and remove the sample.env that is not in both front and back.

Please carefully read through these documents. The user can install them but still needs most of the secret keys and credentials that we use.

### CODE REVIEW

**Comment by PeanutPK** [comment]
I think some of the backend needs some clarification but I will request both the frontend and backend dev to check the docs

**Review by Ichi1234 — CHANGES_REQUESTED** [review]
In installation guide for backend you forgot to change the sentence.

2. Make a .env file inside **frontend** directory. Examples of the .env files are in 

to

2. Make a .env file inside **backend** directory. Examples of the .env files are in 

(It should be backend directory not frontend)

**Review by NoMoneyDev — CHANGES_REQUESTED** [review]
>    2. Activate virtual environment
       - For macOS/Linux
        ```shell
        source env/bin/activate
        ```
       - For Windows
        ```shell
        env\Scripts\activate
        ```

You should create a python virtual environment before activating it via these commands.
```cmd
python3 -m venv venv
// for mac
source venv/bin/activate
// for windows
venv/Scripts/activate
```

**Review by PanidaRumriankit — APPROVED** [review]
Frontend side does not seem to have a problem. Approved.

**Review by Ichi1234 — APPROVED** [review]
I follow the installation guide and I can runs erver. Therefore, I approve this PR

**Comment by NoMoneyDev** [comment]
> Clone the repository
```
     git clone https://github.com/PanidaRumriankit/ku-vein.git`
```

There's a ` at the end of the git clone line

Also, you should tell the user to cd into the ku-vein folder after cloning the repository
```bash
cd ku-vein
```

**Review by NoMoneyDev — CHANGES_REQUESTED** [review]
> Clone the repository
```
     git clone https://github.com/PanidaRumriankit/ku-vein.git`
```

There's a ` at the end of the git clone line

Also, you should tell the user to cd into the ku-vein folder after cloning the repository
```bash
cd ku-vein
```

**Review by NoMoneyDev — APPROVED** [review]
Everything looks good now. Approved! 👍🏻

**Pull request merged**
