### PR TITLE
Removed flake8 because duplicate with  flake8_docstring

### PR DESCRIPTION
**Pull request by NoMoneyDev**
Removed flake8 and kept only flake8_docstring in Github actions as they duplicate

### CODE REVIEW

**Comment by Ichi1234** [comment]
Could you add CI for the Django test too?

**Review by Ichi1234 — CHANGES_REQUESTED** [review]
Please add Django CI badge

**Review by Ichi1234 — APPROVED** [review]
Ok

**Comment by NoMoneyDev** [comment]
> Please add Django CI badge

yeg

**Pull request merged**
