### PR TITLE
Q&A

### PR DESCRIPTION
**Pull request by NoMoneyDev**
## What I did

1. Added and modify models
2. Add endpoints for creating/getting Questions and Answers (/qa, /qa/answer)
3. Migrated django
4. Add checks if the editing user_name already exists in the database
5. Add is_anonymous, and pen_name fields to Questions and Answers
6. Add endpoints for editing Q&A, Review, Note
7. Add tests for Q&A, Review, Note PUT Handlers

### CODE REVIEW

**Comment by NoMoneyDev** [comment]
I wanna add some more endpoints, so this PR will be closed for now.

**Comment by NoMoneyDev** [comment]
Haven't wrote tests, PR closed, again...

**Comment by Ichi1234** [comment]
You shouldn't separate the endpoint to answer and question. You can make one endpoint and have argument to find out is frontend dev want all the question or only specific question.

**Review by Ichi1234 — CHANGES_REQUESTED** [review]
You code should pass Django CI

**Comment by NoMoneyDev** [comment]
> You code should pass Django CI

nein hjjkahfkjhsdkjfhkslajhkjh

**Comment by Ichi1234** [comment]
All done?

**Comment by NoMoneyDev** [comment]
> All done?

No, lol

**Comment by NoMoneyDev** [comment]
Need to add upvote, no. of convos in the Q&A, and date/time of each questions and answers.

**Comment by NoMoneyDev** [comment]
Need sorting endpoint aghahgahghahsossogjsifisgf

**Comment by Ichi1234** [comment]
This feature was supposed to be completed last week. -.-

**Review by Ichi1234 — CHANGES_REQUESTED** [review]
1. Why you have 2 BookMarkQuery in db_query (Redeclared 'BookMarkQuery' defined above without usage )
2.  Missing doc string for method in AnswerQuery, QuestionQuery
3. PostFactory have duplicate key
4. Repeat import make previous import be dead code
5. You didn't add QAController in urls.py
6. Your controller is error might error because it doesn't have self

image

image
image

**Comment by Ichi1234** [comment]
Don't forget to resolve conflict

**Comment by NoMoneyDev** [comment]
> 1. Why you have 2 BookMarkQuery in db_query (Redeclared 'BookMarkQuery' defined above without usage )
> 2. Missing doc string for method in AnswerQuery, QuestionQuery
> 3. PostFactory have duplicate key
> 4. Repeat import make previous import be dead code
> 5. You didn't add QAController in urls.py
> 6. Your controller is error might error because it doesn't have self
> 
> image
> 
> image image

fixed la

**Comment by PanidaRumriankit** [comment]
The images you attached are all broken....

**Comment by Ichi1234** [comment]
> > 1. Why you have 2 BookMarkQuery in db_query (Redeclared 'BookMarkQuery' defined above without usage )
> > 2. Missing doc string for method in AnswerQuery, QuestionQuery
> > 3. PostFactory have duplicate key
> > 4. Repeat import make previous import be dead code
> > 5. You didn't add QAController in urls.py
> > 6. Your controller is error might error because it doesn't have self
> > 
> > image
> > image image
> 
> fixed la

Fix la but 60 error????

**Review by Ichi1234 — APPROVED** [review]
Finally! I ran the server and tested everything related to the Q-and-A. I believe there are no issues with this PR anymore.

**Pull request merged**
