### PR TITLE
Added starter code for django

### PR DESCRIPTION
**Pull request by NoMoneyDev**
Added starter code for Django framework

### CODE REVIEW

**Comment by Ichi1234** [comment]
I don't like Django

**Comment by PeanutPK** [comment]
Could you also create a startapp for the forms?
Like `python manage.py startapp reviews`

**Comment by PeanutPK** [comment]
The starter code is okay for me.

**Comment by PanidaRumriankit** [comment]
good starter code for django

**Review by PeanutPK — APPROVED** [review]
Looking good for me

**Review by Ichi1234 — APPROVED** [review]
Yeah, everything is good. You can merge it

**Review by Ichi1234 — CHANGES_REQUESTED** [review]
Wait no! In setting.py you shouldn't input the secret key can you generate new key and put it in .env file

**Review by PanidaRumriankit — CHANGES_REQUESTED** [review]
I think you should create a folder called 'backend' to include these files for separating the backend and frontend parts and making the structure look clean.

**Review by PeanutPK — CHANGES_REQUESTED** [review]
I missed that you accidentally commited a secret key please encrypt the key.

**Review by Ichi1234 — CHANGES_REQUESTED** [review]
You shouldn't push .env to github everything else is fine. (Please regenerate secret-key again) and don't forget to add backend folder.

**Comment by NoMoneyDev** [comment]
I can't commit empty Frontend folder in Git, so there won't be a Frontend folder for now.

**Review by PanidaRumriankit — APPROVED** [review]
Everything looks clean and good now. You also have .gitignore. That's great! Additionally, Please pull request to iteration1 branch instead of the main branch

**Review by Ichi1234 — APPROVED** [review]
Goodjob!

**Review by PeanutPK — APPROVED** [review]
👍

**Pull request merged**
