### PR TITLE
hot fix url changes and more

### PR DESCRIPTION
**Pull request by PeanutPK**
List of bug
- I accidentally used localhost for the main URL
- Add review uses the old constant that is already changes
- Filter review filter all keys even though the key is None

### CODE REVIEW

**Comment by PeanutPK** [comment]
I found that searchFaculty uses my facultyColor but now I changed those constants so I fix it in this PR too

**Comment by PeanutPK** [comment]
There is a lot of bug so I will close for now

**Comment by PeanutPK** [comment]
I fix most of them pls carefully review my PR again

**Review by Ichi1234 — APPROVED** [review]
YES

**Pull request merged**
