### PR TITLE
GitHub ci

### PR DESCRIPTION
**Pull request by NoMoneyDev**
Added pylint, flake8, flake8-docstring, and coverage to Github Actions.

### CODE REVIEW

**Review by Ichi1234 — APPROVED** [review]
Everything looks great. No problem. Approved.

**Review by PeanutPK — CHANGES_REQUESTED** [review]
Each linter shouldn't check init, migrations, or Django default files.

**Review by Ichi1234 — APPROVED** [review]
Ok

**Review by PeanutPK — APPROVED** [review]
Ok

**Pull request merged**
