### PR TITLE
Review card share and many many stuff

### PR DESCRIPTION
**Pull request by PeanutPK**
# What I did do don't know
1. #191 sharing feature. Copy links, Facebook share, and X share.
2. #196 User can delete other user reviews
3. #199 A long line solved by using a break
4. Finished adding the note feature and fix issue #202 with @NoMoneyDev's help
5. Add a review page for each review ID
6. Finished editing review feature #192 
image

### CODE REVIEW

**Comment by PeanutPK** [comment]
@NoMoneyDev Please help me fix the CI or maybe the code

**Comment by PeanutPK** [comment]
CI gonna need changes a lot so I will convert this PR back to draft

**Comment by PeanutPK** [comment]
I finished the edit review feature.

**Comment by PeanutPK** [comment]
Muhahahaha pls review now!!!!

**Review by Ichi1234 — APPROVED** [review]
LGTM

**Comment by PeanutPK** [comment]
no approve

**Comment by PeanutPK** [comment]
let me fix ahhhhhhhh

**Review by Ichi1234 — CHANGES_REQUESTED** [review]
This feature is not working if pdf file is too large. Please set the maximum file banana  and tell the user that your file is too large

**Comment by PeanutPK** [comment]
yes

**Pull request merged**
