### PR TITLE
Information scraping V2

### PR DESCRIPTION
**Pull request by NoMoneyDev**
Edit and fixed issues that subjects name being on different line results in the subject losing part of its name.

### CODE REVIEW

**Review by Ichi1234 — CHANGES_REQUESTED** [review]
Hey, why are over 2000 of our data missing? You should test your code before creating a pull request. I already checked your code to see if you forgot to push the data to GitHub, but it's worse than I thought please fix your code XD.

**Review by Ichi1234 — CHANGES_REQUESTED** [review]
Now our data aren't missing but why does every JSON file have almost 7000 data? (It duplicate) For example, every JSON files have 01685454 data in it. Please check the data before pushing your code.

**Comment by Ichi1234** [comment]
Check before pushing Check before pushing Check before pushing Check before pushing Check before pushing Check before pushing Check before pushing Check before pushing Check before pushing Check before pushing Check before pushing Check before pushing

**Comment by Ichi1234** [comment]
+31,077 lines 💀

**Comment by NoMoneyDev** [comment]
> +31,077 lines 💀
lol hehe

**Review by Ichi1234 — APPROVED** [review]
Good job! Your code is working well.

**Pull request merged**
