### PR TITLE
Adding note frontend

### PR DESCRIPTION
**Pull request by PeanutPK**
# What I ded (did)?
1. some styling for review card
2. search bar now redirect to course page
3. able to add notes
4. pen name for adding note (optional with checkbox)

### CODE REVIEW

**Review by PeanutPK — COMMENTED** [review]
I have test the feature and now it works

**Comment by PeanutPK** [comment]
Don't merge yet let me add some feature

**Comment by PeanutPK** [comment]
I finished the checkbox so now yes

**Review by Ichi1234 — APPROVED** [review]
Look goose to me

**Pull request merged**
