### PR TITLE
Create diagram

### PR DESCRIPTION
**Pull request by NoMoneyDev**
Add diagrams in this PR, so they can go into README or Information Hub

### CODE REVIEW

**Comment by NoMoneyDev** [comment]
Add diagrams here so they can go into README or Information Hub

**Comment by PeanutPK** [comment]
Where is the diagram in the information hub? Add the shortcut in the Diagram on the homepage too

**Comment by PeanutPK** [comment]
Only in the information hub is enough

**Comment by NoMoneyDev** [comment]
PR closed because I don't need to do all this to get my Doman Diagram into the wiki. I can just paste the diagram in there.

**Pull request closed without merging**
