### PR TITLE
Filter key for sorted review and some course page stuff.

### PR DESCRIPTION
**Pull request by PeanutPK**
# What huh woah?
1. Refactor the sorted review from sort and filter_by to filter_key.
2. Add an optional review ID key to the sorted review.
3. Review deletion feature.
4. Grade Pie Chart and effort for course statistics.

# What I didn't do.
1. Other statistic for the course page.
2. Shareable link for the review card.
3. Each reviews its page.
4. The review owner can edit their review.

### Pie Chart
image

### Delete review
image

### The others are backend feature
I just want to do a PR before any further development so my feature on the backend side didn't go to waste.

### CODE REVIEW

**Comment by PeanutPK** [comment]
Seems like my backend causes errors I will fix them first

**Comment by PeanutPK** [comment]
I fixed the test and the bug. Let's go!!!!! Are there any bugs? Please let me know if you have any suggestions on styling, write a comment, and notify me via Discord.

**Comment by PeanutPK** [comment]
Pls tell me why there is an error on deployment I think it is about the force refresh page that I use, but you know I can't read all of the errors except.
image

**Comment by Ichi1234** [comment]
Why it still fail? after add ; XDDD

**Comment by PeanutPK** [comment]
I forgot to mention that I add a new package for the pie chart if u want to see the chart npm install again la

**Comment by PeanutPK** [comment]
Woohoo Vercel approve me now yeahhhhhhhhhhhhhhhhhhh @PanidaRumriankit @Ichi1234 review pls

**Comment by PeanutPK** [comment]
When will everyone review my PR 😭

**Review by PanidaRumriankit — APPROVED** [review]
Frontend side code looks well. Approve.

**Comment by PanidaRumriankit** [comment]
Don't forget to resolve the conflicts na

**Comment by PeanutPK** [comment]
I resolved the conflicts. Those conflicts are from merging a new branch before merging mine. All the fixes have become conflicts, so please review the branch before merging any fixes or stuff.

**Pull request merged**
