### PR TITLE
I create models folder to seperate django model to different file (seperate by each categories)

### PR DESCRIPTION
**Pull request by Ichi1234**
# Did I do?

1. Create new folder called models
2. update all the test file to import new model's path
3. update db_query, db_post, db_put, db_delete to import new model's path
4. update schemas.py to import new model's path

### CODE REVIEW

**Comment by Ichi1234** [comment]
I haven't run server yet. When I arrive at home I will do it. However, if you see this msg and you have free time please run the server and test it. So, I don't need to do it when I arrive at home.

**Comment by Ichi1234** [comment]
Did no one test the server? : (

**Comment by PanidaRumriankit** [comment]
I just opened a pc a min ago..... For others I think they don't regularly check on this project anymore since we have finished the project.

**Comment by PanidaRumriankit** [comment]
If you tested the server, tell me and I will approve, Your code doesn't look it could destroy the server. In other words, I trust you.

**Comment by PanidaRumriankit** [comment]
Oh k

**Review by PanidaRumriankit — APPROVED** [review]
Your commit gonna rise up to the sky. GG

**Pull request merged**
