### PR TITLE
Q&A

### PR DESCRIPTION
**Pull request by NoMoneyDev**
Add course field to Question POST.
Add course to /qa GET responding values.
Add behavior when changing user_name to also change pen_name in non-anonymous Q&A/Review/Notes.

### CODE REVIEW

**Comment by PeanutPK** [comment]
I don't know much about this feature but I will try my best to review na

**Review by Ichi1234 — CHANGES_REQUESTED** [review]
There is no endpoint for delete the comment and The feature for delete question isn't working

image

**Comment by Ichi1234** [comment]
I think it's schema problem

**Comment by NoMoneyDev** [comment]
Fixed delete comment and question is working

**Review by Ichi1234 — APPROVED** [review]
I test everything about Q&A and now everything is working. Thx for your hardwork.

**Comment by NoMoneyDev** [comment]
This PR solved #187

**Review by Ichi1234 — CHANGES_REQUESTED** [review]
When I change the name of user. It's error

**Review by Ichi1234 — APPROVED** [review]
I create new qa and change the username and value in qa is change too. So, goodjob!

**Pull request merged**
