### PR TITLE
HOTFIX: Can't filter Note

### PR DESCRIPTION
**Pull request by Ichi1234**
1. Fix filter note 
2. add History endpoint

### CODE REVIEW

**Review by PanidaRumriankit — APPROVED** [review]
as you should

**Comment by PanidaRumriankit** [comment]
wait the tests are not passed

**Review by PanidaRumriankit — CHANGES_REQUESTED** [review]
review tests

**Comment by Ichi1234** [comment]
> wait the tests are not passed

Skill issued

**Comment by PanidaRumriankit** [comment]
I am sorry to hear that.

**Comment by Ichi1234** [comment]
> I am sorry to hear that.

Now it's passed. MERGE IT

**Comment by Ichi1234** [comment]
HaHaHAHAHAHAA

**Review by PanidaRumriankit — APPROVED** [review]
Since the tests is all passed. ok

**Pull request merged**
