### PR TITLE
Frontend starter code

### PR DESCRIPTION
**Pull request by PeanutPK**
Please review the starter code and gitignore files. I have separate gitignore for the backend and frontend so there may be an error ignoring those files.

### CODE REVIEW

**Review by Ichi1234 — APPROVED** [review]
I don't know much about frontend but I think this code seems good.

**Review by PanidaRumriankit — CHANGES_REQUESTED** [review]
Personally, I don't think we should push .idea to the repository. Could you please add .idea to .gitignore?

**Comment by PeanutPK** [comment]
> Personally, I don't think we should push .idea to the repository. Could you please add .idea to .gitignore?

I have removed .idea and added them to gitignore.

**Review by PanidaRumriankit — APPROVED** [review]
Everything looks perfect now. Approved.

**Pull request merged**
