### PR TITLE
Github actions aren't taking .env varibales

### PR DESCRIPTION
**Pull request by NoMoneyDev**
Added a step where github cis will take in repos secrets in to its .env

### CODE REVIEW

**Review by PeanutPK — APPROVED** [review]
yes

**Review by Ichi1234 — CHANGES_REQUESTED** [review]
Try merge main and test is it really work?

**Comment by NoMoneyDev** [comment]
> Try merge main and test is it really work?

you rejected the pr. I can't merge, you donut.

**Comment by Ichi1234** [comment]
Merge main in local. Then, push it

**Review by PeanutPK — CHANGES_REQUESTED** [review]
Okn't

**Comment by NoMoneyDev** [comment]
It works now EEEEEEEEEEEEEEEEEEEEEEEEEEE

**Review by Ichi1234 — APPROVED** [review]
Good job!! Please notify me when you finish something. I need to check to see if you are done. You can notify me on our Discord; it's the fastest way to get my response.

**Review by PeanutPK — APPROVED** [review]
🫡 👍

**Pull request merged**
