### PR TITLE
Fixed sort by upvote does not work 

### PR DESCRIPTION
**Pull request by PeanutPK**
# What did I do? Yes man (Only in the review card real)
1. Removed unused file.
2. Removed unused method.
3. Fix the bug sort by upvoting in the front end part.

https://github.com/user-attachments/assets/7747937c-0183-4228-8e37-9fe03add8f2e

### CODE REVIEW

**Review by PanidaRumriankit — CHANGES_REQUESTED** [review]
Everything looks good I think but I would like to ask for some changes. Since we doing this website in Thai, it would be better if you use Thai instead of English in "Instructor: " and "author: ". You could use "อาจารย์: " and "โดย: " ( just a suggestion).

Question: The gif screenshot you attached with this pr is the bug right? or it is what the upvote looks after you fixed the bug?

**Comment by PanidaRumriankit** [comment]
Oh, it's a video not a gif.

**Comment by PeanutPK** [comment]
It's a bug 2 days ago and doesn't relate to this bug fix. I just want to add some meme videos.

**Comment by PanidaRumriankit** [comment]
### Ummm

**Comment by PeanutPK** [comment]
> Everything looks good I think but I would like to ask for some changes. Since we doing this website in Thai, it would be better if you use Thai instead of English in "Instructor: " and "author: ". You could use "อาจารย์: " and "โดย: " ( just a suggestion).
> 
> Question: The gif screenshot you attached with this pr is the bug right? or it is what the upvote looks after you fixed the bug?

For "Instructor" I will use "ผู้สอน" instead and I changed the word author to "โดย". I feel strange writing Thai words in the code but I get that the main group of students we want to approach is every student in the university, which is mostly Thai students.

410227750_340390475300216_4084292599498464766_n

**Comment by PanidaRumriankit** [comment]
How about grade? It is still "Grade: "

**Comment by PeanutPK** [comment]
I am sorry please don't kill me I just forgo

**Comment by PeanutPK** [comment]
image

## Current Review Card
Please let me know if u want any change

**Pull request merged**
