### PR TITLE
Update name feature

### PR DESCRIPTION
**Pull request by NoMoneyDev**
Add change_username function to update user_name in db.

### CODE REVIEW

**Review by Ichi1234 — CHANGES_REQUESTED** [review]
This makes me laugh but please change the response msg to a real response msg not a banana. However, the update function is working completely fine.

image

**Comment by Ichi1234** [comment]
If you make a new factory method in db_post to update the user name. It will save me a lot of time and please have the  Exception Handling for missing email parameter. Look at my format I already write a lot of endpoint for you.

**Review by Ichi1234 — APPROVED** [review]
Goodjob

**Comment by NoMoneyDev** [comment]
will change PATCH to PUT so, this PR is closed for now.

**Comment by NoMoneyDev** [comment]
I cant npm run dev for some reason so, I will yeet this into main.

**Comment by PeanutPK** [comment]
> I cant npm run dev for some reason so, I will yeet this into main.

Nah

**Review by PeanutPK — CHANGES_REQUESTED** [review]
Please fix first don't yeet

**Review by PeanutPK — APPROVED** [review]
Works now ok

**Review by Ichi1234 — APPROVED** [review]
LGTM

**Pull request merged**
