### PR TITLE
Create course page and template for Note and Q&A page

### PR DESCRIPTION
**Pull request by PeanutPK**
# What I did
1. The layout for the course page.
2. navigation bar for navigating through three sections.
3. Template for the Q&A and Note section.
4. Implement a simple review filter in the backend (Kasidet told me he would change the current one).

## layout
image

## Review page
image

## Templates
image

# What I didn't do
1. Check and apply dark mode 100% to all of them but I think it would work.

I will stop working now and read for the upcoming quiz until tomorrow so feel free to leave a comment and request changes in this PR thanks.

### CODE REVIEW

**Comment by PeanutPK** [comment]
I forgot to add grades to the page but I will implement it later.

**Comment by PeanutPK** [comment]
I will fix some bugs for a short moment don't approve

**Review by Ichi1234 — COMMENTED** [review]
Everything is good, but when the user uses the search, the search bar should not disappear when they choose a faculty. I think this is not ideal because the user will not know that they need to click the search bar again to search for the subject.

**Comment by PeanutPK** [comment]
> Everything is good, but when the user uses the search, the search bar should not disappear when they choose a faculty. I think this is not ideal because the user will not know that they need to click the search bar again to search for the subject.

That is not what I am doing because Panida is currently working on that feature so now it is just a course page from clicking the legend of the review cards.

**Review by Ichi1234 — APPROVED** [review]
Ok, I will approve it.

**Comment by PanidaRumriankit** [comment]
@Ichi1234 I am finding a way to get rid of this problem. However, I still haven't found a solution.
@PeanutPK kk. Everything looks good. Let me merge.

**Pull request merged**
